insetPosition = 'lower right'
insetWidth = 2.5
insetHeight = 1.0
insetBorderPad = 5.0
markersize = 12
linewidth = 1.5
linestyle = '-'
fitColors = ['red', 'green']
lineColors = ['C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9']
labelPadX = 5.0
labelPadY = 3.5
labelPadZ = 20
cmap = 'turbo'
contourFillLevels = 100
contourLevels = 6
contourLinewidths = .4 # Not overrideable
baxpad = .2
majorTickSize = [1.6,8]
minorTickSize = [.8,4]
amountOfZTicks = 6